chore: add golden tests (#75)
cdepillabout/password pull request #82
Opened 2024-10-07 21:54 UTC by blackheaven

2024-10-19 06:25 UTC, Vlix commented
@blackheaven
If you could rebase this on `master`, that'd fix the CI again :)

2024-10-19 14:10 UTC, blackheaven commented
Done, thanks.

2024-10-19 14:44 UTC, Vlix requested changes
Looks good overall, just a few things that look irregular

2024-10-19 17:03 UTC, blackheaven commented on password/test/golden/Scrypt_outputLength16.golden
I didn't change the right parameters

2024-10-20 02:00 UTC, Vlix approved these changes

2024-10-20 13:49 UTC, merged